services:
    odiseo_vendor.event_listener.admin.menu_builder:
        class: Odiseo\SyliusVendorPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    odiseo_vendor.event_listener.vendor_logo_upload:
        class: Odiseo\SyliusVendorPlugin\EventListener\VendorLogoUploadListener
        arguments:
            - '@odiseo_vendor.uploader.vendor_logo'
        tags:
            - { name: kernel.event_listener, event: odiseo_vendor.vendor.pre_create, method: uploadLogo }
            - { name: kernel.event_listener, event: odiseo_vendor.vendor.pre_update, method: uploadLogo }
