services:
    sylius.fixture.product:
        class: Odiseo\SyliusVendorPlugin\Fixture\ProductFixture
        arguments:
            - '@sylius.manager.product'
            - '@sylius.fixture.example_factory.product'
        tags:
            - { name: sylius_fixtures.fixture }

    sylius.fixture.example_factory.product:
        class: Odiseo\SyliusVendorPlugin\Fixture\Factory\ProductExampleFactory
        arguments:
            - '@odiseo_sylius_vendor_plugin.repository.vendor'
            - '@sylius.factory.product'
            - '@sylius.factory.product_variant'
            - '@sylius.factory.channel_pricing'
            - '@sylius.generator.product_variant'
            - '@sylius.factory.product_attribute_value'
            - '@sylius.factory.product_image'
            - '@sylius.factory.product_taxon'
            - '@sylius.uploader.image'
            - '@sylius.generator.slug'
            - '@sylius.repository.taxon'
            - '@sylius.repository.product_attribute'
            - '@sylius.repository.product_option'
            - '@sylius.repository.channel'
            - '@sylius.repository.locale'
            - '@sylius.repository.tax_category'
            - '@file_locator'

    odiseo_sylius_vendor_plugin.fixture.vendor:
        class: Odiseo\SyliusVendorPlugin\Fixture\VendorFixture
        arguments:
            - '@odiseo_sylius_vendor_plugin.manager.vendor'
            - '@odiseo_sylius_vendor_plugin.fixture.example_factory.vendor'
        tags:
            - { name: sylius_fixtures.fixture }

    odiseo_sylius_vendor_plugin.fixture.example_factory.vendor:
        class: Odiseo\SyliusVendorPlugin\Fixture\Factory\VendorExampleFactory
        arguments:
            - '@odiseo_sylius_vendor_plugin.factory.vendor'
            - '@odiseo_sylius_vendor_plugin.uploader.vendor_logo'
            - '@sylius.repository.channel'
            - '@sylius.repository.locale'
            - '@file_locator'
