imports:
    - { resource: fixtures/shop_configuration.yaml }
    - { resource: fixtures/tshirt.yaml }
    - { resource: fixtures/cap.yaml }
    - { resource: fixtures/dress.yaml }
    - { resource: fixtures/jeans.yaml }
    - { resource: fixtures/promotion.yaml }
    - { resource: fixtures/custom_fixtures.yaml }

parameters:
    env(ODISEO_FIXTURES_HOSTNAME): 'localhost'
    env(ODISEO_FIXTURES_THEME_NAME): ~

sylius_fixtures:
    suites:
        vendor:
            listeners:
                orm_purger: ~
                logger: ~
