imports:
    - { resource: "app/twig_hooks/**/*.yaml" }
    - { resource: "app/resources/**/*.yaml" }
    - { resource: "app/grids/**/*.yaml" }
    - { resource: "app/fixtures/**/*.yaml" }

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        odiseo_vendor_logo:
            local:
                directory: "%sylius_core.public_dir%/media/vendor-logo"
                create: true
    filesystems:
        odiseo_vendor_logo:
            adapter: odiseo_vendor_logo

liip_imagine:
    loaders:
        odiseo_vendor_logo:
            filesystem:
                data_root: "%kernel.project_dir%/public/media/vendor-logo"
    filter_sets:
        odiseo_vendor_logo:
            data_loader: odiseo_vendor_logo
            filters:
                thumbnail: { size: [350, 350], mode: outbound }
